apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" . }}-creds-{{ .Values.env }}
  namespace: {{ .Values.namespace }}-{{ .Values.env }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}